<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Categoria;

class ProductoSeeder extends Seeder
{
    public function run()
    {
        // Obtener los IDs de las categorías por nombre
        $categorias = Categoria::pluck('id_categoria', 'nombre');

        DB::table('productos')->insert([
            [
                'nombre' => 'Hoodie Blazing Gris',
                'descripcion' => 'Hoodie Gris talla XXXL',
                'precio' => 25.99,
                'imagen' => 'buzogris.jpg',
                'talla' => 'XXXL',
                'color' => 'Gris',
                'activo' => true,
                'id_categoria' => $categorias['Buzos'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Soft Blanca',
                'descripcion' => 'Camiseta de algodón blanca talla M',
                'precio' => 75.50,
                'imagen' => 'camisablanca.jpg',
                'talla' => 'M',
                'color' => 'Blanco',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Soft Negra',
                'descripcion' => 'Camiseta de algodón negra talla M',
                'precio' => 25.99,
                'imagen' => 'camisetanegra.jpg',
                'talla' => 'M',
                'color' => 'Negro',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Esqueleto Negro',
                'descripcion' => 'Esqueleto con estampado de la marca',
                'precio' => 52.00,
                'imagen' => 'esqueleto.jpg',
                'talla' => 'M',
                'color' => 'Negro',
                'activo' => true,
                'id_categoria' => $categorias['Camisas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crop Top',
                'descripcion' => 'Rosado perfecto para el verano',
                'precio' => 28.00,
                'imagen' => 'camisarosada.jpg',
                'talla' => 'S',
                'color' => 'Rosado',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Hoodie Blanco',
                'descripcion' => 'Hoodie con estampado Blazing cómodo',
                'precio' => 47.00,
                'imagen' => 'buzoblanco.jpg',
                'talla' => 'M',
                'color' => 'Blanco',
                'activo' => true,
                'id_categoria' => $categorias['Buzos'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Blanca Spider-Women',
                'descripcion' => 'Estampada de tres personajes femeninos del universo de Spider-Man.',
                'precio' => 90.00,
                'imagen' => 'spider.jpg',
                'talla' => 'M',
                'color' => 'Blanco',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Blanca Demon Slayer',
                'descripcion' => 'Para los fans del anime Demon Slayer: Kimetsu no Yaiba',
                'precio' => 35.00,
                'imagen' => 'kimetsu no yaiba.jpg',
                'talla' => 'M',
                'color' => 'Blanco',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Negra Sailor Moon',
                'descripcion' => 'Homenaje a un clásico del anime, Sailor Moon',
                'precio' => 25.00,
                'imagen' => 'sailor moon.jpeg',
                'talla' => 'M',
                'color' => 'Negro',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Negra Dragon Ball Z',
                'descripcion' => 'Imprescindible para los fans de Dragon Ball Z',
                'precio' => 56.00,
                'imagen' => 'vegetta.jpeg',
                'talla' => 'L',
                'color' => 'Negro',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Negra Doraemon',
                'descripcion' => 'Artículo imprescindible para los fans de Doraemon',
                'precio' => 2300.00,
                'imagen' => 'doraemon.jpeg',
                'talla' => 'L',
                'color' => 'Negro',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Negra Totoro',
                'descripcion' => 'Diseño futurista y mecánico del personaje Totoro',
                'precio' => 5600.00,
                'imagen' => 'totoro.jpeg',
                'talla' => 'M',
                'color' => 'Negro',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Negra Super Mario Bros',
                'descripcion' => 'Diseño reinterpretando a Yoshi como un robot futurista',
                'precio' => 5600.00,
                'imagen' => 'mariobross.jpeg',
                'talla' => 'M',
                'color' => 'Negro',
                'activo' => true,
                'id_categoria' => $categorias['Camisetas'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
